features/create_record_of_guidance.feature
A very high-level "walking skeleton" feature, to allow us to keep moving.
What do people think?
=> Add create record of guidance feature @wipped

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/appointment_summaries_controller.rb, app/models/appointment_summary.rb, app/views/appointment_summaries/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_alerts.html.erb, config/routes.rb, db/migrate/20150224170109_create_appointment_summaries.rb, db/schema.rb, features/step_definitions/record_of_guidance_steps.rb, features/support/env.rb, features/support/pages/appointment_summary_page.rb, spec/models/appointment_summary_spec.rb
First cut of capturing the details of the delivered guidance. Just capturing the attendee's name currently.
=> Capture guidance

app/controllers/appointment_summaries_controller.rb, app/mailers/output_document_mailer.rb, app/services/issue_output_document.rb, config/environments/test.rb, features/step_definitions/record_of_guidance_steps.rb, features/support/env.rb, spec/mailers/output_document_mailer_spec.rb, spec/services/issue_output_document_spec.rb
Another go at #9.
The Cucumber stuff is a bit ropey.
=> Email output document - redux

features/step_definitions/record_of_guidance_steps.rb
=> Don't stub out PDF rendering in Cuke

spec/controllers/appointment_summaries_controller_spec.rb, spec/rails_helper.rb
It's debatable that such a test is required but here you go @andrewgarner
=> Test that authentication is required

db/migrate/20150304080627_devise_create_users.rb, db/schema.rb
=> Add users to database schema

db/migrate/20150306153421_add_name_to_user.rb, db/migrate/20150306153657_add_organisation_to_user.rb, db/schema.rb
Simplest thing to allow us to run the pilots.
=> Add name and organisation to user

db/migrate/20150312103336_change_reference_number_to_string.rb, db/schema.rb
Per discussion concerning number versus string
=> Make reference_number a string

db/migrate/20150313163656_devise_invitable_add_to_users.rb, db/schema.rb
Adds devise_invitable columns to the `users` table.
=> Add devise_invitable columns to users table

app/models/appointment_summary.rb, app/templates/output_document.html.erb, app/views/appointment_summaries/new.html.erb, app/views/styleguide/pages/input_v2.html.erb, spec/models/appointment_summary_spec.rb
They will no longer be using this tool.
=> Remove Citizens Advice

app/models/appointment_summary.rb, spec/models/appointment_summary_spec.rb
These will be used to determine which variation of the output document to create
=> Add predicates to determine the type of guidance provided

app/assets/javascripts/application.js, app/assets/javascripts/init.js, app/assets/javascripts/postcode-lookup.js, app/views/appointment_summaries/new.html.erb, app/views/layouts/application.html.erb, app/views/styleguide/pages/input.html.erb, bower.json
Adds postcode lookup with fallback address search, based on ideal-postcodes.co.uk
=> Postcode lookup

app/assets/javascripts/postcode-lookup.js
Domain and usage restrictions allow this to be public.
=> Set Postcodes.io API key

app/controllers/appointment_summaries_controller.rb, app/templates/output_document.html.erb, app/views/appointment_summaries/new.html.erb, app/views/appointment_summaries/preview.html.erb, config/routes.rb, features/create_record_of_guidance.feature, features/step_definitions/record_of_guidance_steps.rb, features/support/pages/record_of_guidance_preview_page.rb, spec/domain/output_document_spec.rb
@aduggin's front-end magic is going into this
=> [WIP] HTML preview of output document

app/assets/javascripts/consent.js
This should be good enough for now.
=> Assume consent is given if errors displayed

app/assets/stylesheets/components/_alert.scss, app/helpers/application_helper.rb, app/models/appointment_summary.rb, app/views/appointment_summaries/new.html.erb, app/views/shared/_alerts.html.erb, config/locales/en-GB.yml, config/locales/en.yml, spec/models/appointment_summary_spec.rb
Giving error handling some :heart:
=> Error messages

app/views/appointment_summaries/preview.html.erb
- rather iterate the columns in the DB
=> Remove manual enumeration of fields in preview

db/migrate/20150326152759_add_value_of_pension_pots_is_approximate_to_appointment_summary.rb, db/schema.rb
In preparation for recording whether the value of pension pots is an approximate value.
=> Add value_of_pension_pots_is_approximate to appointment_summaries table

app/assets/javascripts/pension-pot-accuracy.js, app/controllers/appointment_summaries_controller.rb, app/views/appointment_summaries/new.html.erb, features/step_definitions/record_of_guidance_steps.rb, features/support/pages/appointment_summary_page.rb
Dependent on https://github.com/guidance-guarantee-programme/output/pull/76
=> Record whether pension pots value is approximate

app/domain/output_document.rb, app/templates/output_document_ineligible.html.erb, spec/domain/output_document_spec.rb
Renamed branch which closed the previous PR...
Addresses #79
=> Extract `lead` into `OutputDocument`

app/domain/output_document.rb, config/initializers/date_formats.rb, spec/domain/output_document_spec.rb
=> Format date consistent with the GOV.UK service manual

app/domain/output_document.rb, app/templates/output_document_cover_letter.html.erb, spec/domain/output_document_spec.rb
Arguably the cover letter could be part of the introduction page, any thoughts?
=> Add placeholder for cover letter in output document

db/migrate/20150401110927_remove_name_and_address_from_appointment_summaries.rb, db/schema.rb
=> Remove `name` and `address` from `appointment_summaries`

app/domain/csv_renderer.rb, app/domain/output_document.rb, app/domain/output_document/csv_row_renderer.rb, spec/domain/csv_renderer_spec.rb, spec/domain/output_document_csv_row_renderer_spec.rb, spec/domain/output_document_spec.rb
=> CSV renderer for `OutputDocument`s

app/models/appointment_summaries_batch.rb, app/models/appointment_summary.rb, app/models/batch.rb, app/services/create_batch.rb, db/migrate/20150408150105_create_batches.rb, db/migrate/20150408152646_create_appointment_summaries_batches.rb, db/schema.rb, spec/models/appointment_summary_spec.rb, spec/models/batch_spec.rb, spec/services/create_batch_spec.rb
First attempt at batching up `AppointmentSummary`s to be processed and uploaded to the print house, thoughts?
=> AppointmentSummary Batching

config/cucumber.yml, features/covering_letter.feature, features/ineligibility_letter.feature, features/record_of_guidance_contents.feature
Taken verbatim from the PDF-generation-only repo. I think they're valid as is for this one.
=> Add document-contents features

features/authentication.feature, features/create_record_of_guidance.feature, features/preview_covering_letter.feature, features/preview_ineligibility_letter.feature, features/preview_record_of_guidance.feature, features/record_of_guidance_contents.feature, features/step_definitions/authentication_steps.rb, features/support/authentication.rb, features/support/pages/user_sign_in_page.rb
=> Better login for Cucumber

Procfile, app.json, lib/tasks/output_documents.rake
The schedule has to be added manually as it can't be configured via `app.json`
=> Process output documents schedule

app/services/upload_to_print_house.rb, spec/services/upload_to_print_house_spec.rb
Printhouse no longer requires one to trigger a print run
=> Don't upload a trigger file

config/environments/production.rb
=> Appease Rubocop

app/models/csv_upload_job.rb, app/services/process_output_documents.rb, app/services/upload_to_print_house.rb, spec/models/csv_upload_job_spec.rb, spec/services/process_output_documents_spec.rb, spec/services/upload_to_print_house_spec.rb
`CSVUploadJob` is a weird name, its a class that encapsulates the logic of turning a `Batch` into everything needed to send to the print house (i.e. file contents, file paths). Can anyone think of a better name?
=> Upload trigger files on successful upload of data files to print house

db/migrate/20150427100026_add_devise_recoverable_to_users.rb, db/schema.rb
Migration pulled out of [output#143](https://github.com/guidance-guarantee-programme/output/pull/143)
=> Add Devise recoverable columns to users table

app/views/devise/sessions/new.html.erb
=> Use Bootstrap style for login button

app/helpers/application_helper.rb, app/views/appointment_summaries/new.html.erb, app/views/shared/_errors.html.erb
Going to need this for the Devise forms that will be pulled in soon
=> Extract error message generation into a helper

spec/services/upload_to_print_house_spec.rb
- asserts upload order
- mocks Net::SFTP rather than a private method on our class. Net::SFTP is the de facto standard for SFTP in Ruby, and has a stable API, so i think that mocking it is acceptable in this case given the ease of refactoring that this allows
=> Refactor upload_to_print_house_spec

.rubocop.yml, features/back_from_preview.feature, features/step_definitions/back_from_preview_steps.rb, features/support/matchers/have_checkbox_state.rb, features/support/pages/appointment_summary_page.rb, features/support/site_prism/radio_button_container.rb, features/support/site_prism/radio_button_group.rb
Adds first-class support of radio buttons to SitePrism.
Note: this PR is to add a feature to an in progress branch, its not to go to master!
=> Add "back from preview" feature

Procfile
Alert [Dead Man's Snitch](https://deadmanssnitch.com/) when output documents are processed
=> Add monitoring to process_output_documents scheduled jobs

db/migrate/20150511110601_remove_name_from_users.rb, db/schema.rb
=> Remove redundant `name` column from `users`

.rubocop.yml, app/assets/javascripts/consent.js, app/assets/javascripts/eligibility.js, app/assets/javascripts/init.js, app/assets/javascripts/pension-pot-input.js, app/assets/stylesheets/base/_forms.scss, app/assets/stylesheets/components/_fixed-bar.scss, app/assets/stylesheets/layout/_input.scss, app/controllers/appointment_summaries_controller.rb, app/views/appointment_summaries/_preview_form.html.erb, app/views/appointment_summaries/preview.html.erb, features/back_from_preview.feature, features/step_definitions/back_from_preview_steps.rb, features/support/matchers/have_checkbox_state.rb, features/support/pages/appointment_summary_page.rb, features/support/pages/preview_page.rb, features/support/site_prism/radio_button_container.rb, features/support/site_prism/radio_button_group.rb
Still to do:
- CSS
- Javascript needs to be properly initialised from the form on the new appointment summary page
=> Add back button to preview page

app/views/appointment_summaries/_preview_form.html.erb
=> Prevent double submission of form

app/assets/stylesheets/base/_forms.scss, app/views/devise/sessions/new.html.erb
To accommodate less technically savvy guiders with long email addresses.
How do you like that BEM @aduggin ?
=> Make login form fields wider

app/controllers/styleguide_controller.rb, app/views/styleguide/index.html.erb, config/routes.rb
Maybe better to just remove the styleguide from this app?
=> Fix styleguide

db/migrate/20160225114042_add_apointment_type_to_appointment_summaries.rb, db/schema.rb
In preparation for appointment type attributes.
=> Add `appointment_type` column to schema

app/controllers/admin/appointment_summaries_controller.rb, app/forms/appointment_summary_browser.rb, app/services/appointment_summary_csv.rb, app/views/admin/appointment_summaries/index.html.erb, config/initializers/csv_renderer.rb, features/appointment_summary_browser.feature, features/step_definitions/appointment_summary_steps.rb, features/support/pages/appointment_summary_browser_page.rb, spec/factories.rb, spec/forms/appointment_summary_browser_spec.rb, spec/services/appointment_summary_csv_spec.rb
Adds export to CSV capabilities to the appointment summaries dashboard.
=> Export Appointment Summaries to CSV

app/controllers/appointment_summaries_controller.rb, app/views/appointment_summaries/new.html.erb, db/migrate/20160418095403_add_requested_digital_to_appointment_summaries.rb, db/schema.rb, features/digital_summary.feature, features/step_definitions/back_from_preview_steps.rb, features/step_definitions/digital_summary_steps.rb, features/support/fixtures.rb, features/support/pages/appointment_summary_page.rb
This should be merged in accordance with the timelines of the rollout plan.
=> Digital summary

app/services/appointment_summary_csv.rb, spec/services/appointment_summary_csv_spec.rb
Adds the newly added field to report upon.
=> Add `requested_digital` field to CSV export

app/services/appointment_summary_csv.rb, spec/services/appointment_summary_csv_spec.rb
Adds the `created_at` timestamp to the CSV output in the necessary
locale.
=> Add `created_at` timestamp to CSV output

app/services/appointment_summary_csv.rb, app/services/csv_generator.rb
Uses the recently introduced `CsvGenerator` from our reporting project.
This is good for now while I extract a gem to share between both
projects.
=> Abstract CSV generation

db/migrate/20160712095513_add_number_of_appointments_to_appointment_summary.rb, db/schema.rb
-- DO NOT MERGE --
until the related code PR #211 has been approved
=> Add number_of_appointments field to DB

db/migrate/20160715124444_add_count_of_pension_pots.rb, db/schema.rb
=> Appendix C fields DB migration

app/assets/javascripts/additional-appointment.js, app/assets/javascripts/application.js, app/assets/javascripts/init.js, app/assets/javascripts/pension-pot-input.js, app/assets/stylesheets/components/_form.scss, app/controllers/appointment_summaries_controller.rb, app/models/appointment_summary.rb, app/services/appointment_summary_csv.rb, app/services/create_batch.rb, app/views/appointment_summaries/new.html.erb, db/migrate/20160713134849_change_to_digital_by_default.rb, db/schema.rb, features/step_definitions/back_from_preview_steps.rb, features/step_definitions/record_of_guidance_steps.rb, features/support/fixtures.rb, features/support/pages/appointment_summary_page.rb, spec/factories.rb, spec/models/appointment_summary_spec.rb, spec/services/appointment_summary_csv_spec.rb, spec/services/create_batch_spec.rb
This combines the following PR's
#211 
#212 
#213 
For deployment on 20th July 2015
=> Deployment - 2016-07-20

db/migrate/20160721095104_add_notification_fields.rb, db/schema.rb
This will allow a link to be sent via email
to users who requests a digital version
This needs to be merged before PR #216
=> Add email and notification ID fields to DB

app/controllers/admin/appointment_summaries_controller.rb, app/forms/appointment_summary_browser.rb, app/views/admin/appointment_summaries/index.html.erb, spec/forms/appointment_summary_browser_spec.rb
Add additional search options to admin interface.
Search does a case insensitive wildcard like match
using the value provided.
=> Search appointment by surname and reference

app/controllers/admin/appointment_summaries_controller.rb, app/models/appointment_summary.rb, app/views/admin/appointment_summaries/edit.html.erb, app/views/admin/appointment_summaries/index.html.erb, config/routes.rb, features/delivery_methods.feature, features/email_notification.feature, features/step_definitions/delivery_methods_steps.rb, features/support/pages/appointment_summary_browser_page.rb, features/support/pages/appointment_summary_edit_page.rb, spec/models/appointment_summary_spec.rb
Allow correction and resend of emails if they have
been input incorrectly.
=> Edit and resend email

app/models/appointment_summary.rb, spec/models/appointment_summary_spec.rb
This makes:
"d henry@test.com" an invalid email address
=> Don't allow spaces in email address

app/models/appointment_summary.rb, app/services/appointment_summary_csv.rb, app/views/appointment_summaries/new.html.erb, db/migrate/20161017142943_add_retirement_income_fields.rb, db/schema.rb, features/step_definitions/back_from_preview_steps.rb, features/step_definitions/record_of_guidance_steps.rb, features/support/fixtures.rb, features/support/pages/appointment_summary_page.rb, spec/domain/output_document_spec.rb, spec/factories.rb, spec/models/appointment_summary_spec.rb, spec/services/appointment_summary_csv_spec.rb
List of options for the type of income the customer
is expecting in retirement.
We have also remove the question asking if you
have addiitonal income in retirement as it is cover
by the results of this question.
=> [DO NOT MERGE] Add retirement income fields

db/migrate/20161101141726_remove_users_null_constraints.rb, db/schema.rb
This constraint is incompatible with users which are
pushed form signon.
=> Remove null constrain from users

app/domain/csv_renderer.rb, app/domain/output_document.rb, app/views/appointment_summaries/new.html.erb, db/migrate/20161207154853_add_supplementary_pension_transfers.rb, db/schema.rb, features/preview_record_of_guidance.feature, features/record_of_guidance_contents.feature, features/step_definitions/preview_record_of_guidance_contents_steps.rb, features/step_definitions/record_of_guidance_contents_steps.rb, features/support/pages/appointment_summary_page.rb, spec/domain/csv_renderer_spec.rb
Add a checkbox to allow this section to be rendered
on the summary document.
=> [DO NOT MERGE] 'Transfer of Pension Pot' supplementary section

.buildpacks, app.json
This only fixes the multiple buildpack issue. 
It does not attempt to updated all app.json settings.
=> Replace multi-buildpack config

.travis.yml, app/constraints/authenticated_user.rb, config/routes.rb, spec/rails_helper.rb, spec/requests/sidekiq_auth_spec.rb, spec/support/user_helpers.rb
This ensures only authenticated users are permitted access
to the sidekiq control panel.
=> Authenticate for sidekiq panel

.travis.yml
We use pipelines elsewhere so we should here too.
=> Favour heroku pipelines over custom build

app/views/appointment_summaries/summarise_via_tap.html.erb
Improves the content based on updates from the content folks.
=> Add copy from content team

Gemfile, Gemfile.lock
We can use our released gem now it has been pushed to rubygems.
=> Switch to the released gem

app/controllers/appointment_summaries_controller.rb, app/views/appointment_summaries/new.html.erb, features/step_definitions/authentication_steps.rb, features/step_definitions/back_from_preview_steps.rb, features/step_definitions/email_confirmation_steps.rb, features/step_definitions/preview_record_of_guidance_contents_steps.rb, features/step_definitions/record_of_guidance_contents_steps.rb, features/step_definitions/record_of_guidance_steps.rb, features/support/pages/appointment_summary_page.rb
=> Make certain items on the document creation form read only

app/views/appointment_summaries/done.html.erb, app/views/appointment_summaries/index.html.erb, app/views/appointment_summaries/new.html.erb, app/views/appointment_summaries/preview.html.erb
Analytics team have requested improved page titles across
the app
=> Improving the wording of page headers

app/controllers/appointment_summaries_controller.rb
We need to handle the JSON responder to ensure the correct paths are
returned when requesting this action via AJAX.
=> Ensure we preview regenerated summaries

app/views/appointment_summaries/new.html.erb
For customers who are within 6 months of 55yo, the call content
and the summary document is for those aged 55 and over. Therefore
this allow them to adjust the summary document to suit.
=> Guider is able to edit the 'type of appointment' field

app/views/appointment_summaries/confirm.html.erb, app/views/appointment_summaries/new.html.erb, app/views/layouts/application.html.erb, config/locales/en-GB.yml
=> Altering content to make form generic for phone and f2f appointments

app/assets/javascripts/email-validation.js, spec/features/email_address_suggestions_spec.rb
Was positive I recalled testing this but apparently not.
Picked up by Aman yesterday, the ability to click the suggested email to
=> Fix click to fill behaviour on email suggestion

Gemfile, Gemfile.lock, app/models/appointment_summary.rb, app/views/appointment_summaries/new.html.erb
Late requirement clarification.
**Option**
**Result**
=> Add option to select ‘no cover letter customisation’

Gemfile, Gemfile.lock
Incorporates the latest updates for the output templates.
=> Bump templates for latest updates

.travis.yml, Gemfile, Gemfile.lock, spec/support/poltergeist.rb
The binaries gem doesn't play nice with apps that use `phantomjs` since
it clobbers their binaries. Using this one here makes working on
Pension Wise applications much easier.
=> Use the basic `phantomjs` gem

Gemfile.lock
This subtly changes the text around time restrictions with adjustable
income products.
=> Remove time restriction from adjustable income

app.json
We should move away from the multipack and configure our buildpacks
individually. I'll do this shortly.
=> Switch to our fork temporarily

Gemfile.lock, app/models/appointment_summary.rb, app/views/appointment_summaries/new.html.erb, spec/support/pages/appointment_summary_page.rb
Adds the fixed term annuity covering letter option.
=> Add a further covering letter option

app/controllers/admin/appointment_summaries_controller.rb, app/forms/appointment_summary_browser.rb, app/views/admin/appointment_summaries/index.html.erb, spec/forms/appointment_summary_browser_spec.rb
Adds the telephone and requested digital filters to the admin reporting.
They both default to unspecified so will include all results unless a
particular value is selected.
=> Adds further reporting filters

Gemfile, Gemfile.lock, lib/tasks/export.rake
This is for analysis by the data team.
=> Export appointment summaries as CSV to blob store

Gemfile, Gemfile.lock, app/controllers/appointment_summaries_controller.rb, app/domain/output_document.rb, app/domain/output_document/html_renderer.rb, app/jobs/notify_due_diligence_via_email.rb, app/models/appointment_summary.rb, app/views/appointment_summaries/confirm.html.erb, app/views/appointment_summaries/new.html.erb, config/initializers/notify.rb, db/migrate/20210922105434_add_schedule_type_to_appointment_summary.rb, db/migrate/20210927104120_add_unique_reference_number_to_appointment_summary.rb, db/schema.rb, spec/domain/output_document_spec.rb, spec/factories.rb, spec/features/tap_due_diligence_summary_document_generation_spec.rb, spec/jobs/notify_due_diligence_via_email_spec.rb, spec/models/appointment_summary_spec.rb, spec/support/pages/appointment_summary_page.rb, spec/support/pages/confirmation_page.rb
Allows TPAS agents to create due diligence based summary documents via
the link from TAP.
=> Due diligence summary documents

Gemfile.lock
Adds targets to the links for those contexts where they are displayed
within frames and embeds.
=> Bump templates for link target additions

Gemfile.lock
Bump templates to include new appointment content in summary documents.
=> Bump templates for 2023 year updates

.travis.yml, Gemfile, Gemfile.lock, package-lock.json, package.json
Bumps the templates for year end changes to the summary documents.
=> Year end 2024

config/initializers/govuk_admin_template.rb
This was incorrectly determined.
=> Switch the environment label and styling
