app/jobs/output_document_mailer_job.rb
app/services/issue_output_document.rb
features/step_definitions/record_of_guidance_steps.rb
spec/jobs/output_document_mailer_job_spec.rb
spec/services/issue_output_document_spec.rb

Relying on the built in `ActiveJob`/`ActionMailer` magic meant the PDF attachment for the mail was being generated and then stuck into Redis for later delivery via the Sidekiq worker. Needless to say Redis didn't like this.
This PR adds yet another layer of indirection to the process and I don't like that we have an `AppointmentSummary` being passed around so many times but it should be good enough for the time being.

Use an ActiveJob job to send the mailer

---

app/assets/stylesheets/base/_forms.css.scss
app/controllers/appointment_summaries_controller.rb
app/views/appointment_summaries/new.html.erb
features/step_definitions/record_of_guidance_steps.rb
features/support/pages/appointment_summary_page.rb

I've reviewed the GDS Service Manual guidance on addresses here - https://www.gov.uk/service-manual/user-centred-design/resources/patterns/addresses
Opted for the simplest approach initially which is a text box to collect the address. We may need to break this down into individual address lines later on when we establish requirements with the print provider.
**Needs to be rebased once #21 has been merged.**

Collect postal address of appointment attendee

---

Gemfile
Gemfile.lock
app/assets/stylesheets/base/_forms.css.scss
app/controllers/appointment_summaries_controller.rb
app/models/user.rb
app/views/appointment_summaries/new.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
features/create_record_of_guidance.feature
features/step_definitions/record_of_guidance_steps.rb
features/step_definitions/user_steps.rb
features/support/pages/user_sign_in_page.rb
spec/controllers/appointment_summaries_controller_spec.rb
spec/rails_helper.rb

- Requires a user account to generate a record of guidance
- User account creation is through the console by a sysadmin
- New accounts must be confirmed
- Failed login attempts will cause the account to be locked
- Authenticated sessions will expire after a set period of time

Configure MVP authentication

---

Gemfile
Gemfile.lock
app/controllers/appointment_summaries_controller.rb
app/models/appointment_summary.rb
app/views/appointment_summaries/new.html.erb
db/migrate/20150319084903_remove_email_address_from_appointment_summaries.rb
db/schema.rb
features/step_definitions/record_of_guidance_steps.rb
features/support/pages/appointment_summary_page.rb
spec/models/appointment_summary_spec.rb

This is no longer needed as all output will be issued as white mail.

Remove email address from appointment summaries

---

app/models/appointment_summary.rb
spec/models/appointment_summary_spec.rb

If the attendee does not have a DC pension we don't need to know about their pot size or source of income.
cc/ @aduggin

Only apply certain validation for eligible appointment attendees

---

app/domain/output_document.rb
spec/domain/output_document_spec.rb

This interface ties together the card dealing with batch processing and the one concerning the CSV generation itself

Add placeholder for CSV representation of output docs

---

app/domain/output_document.rb
spec/domain/output_document_spec.rb

Resolves #80 
Let this through without tests?

Use `id` *and* `reference_number` to refer to generated documents

---

app/domain/output_document.rb
app/templates/output_document_introduction.html.erb

Per my comment on the doc, the data dictionary mentions `guider_first_name` but I believe the printhouse are expecting `guider_name` which we already have @andrewgarner ?

Align `OutputDocument` fields with data dictionary

---

app/services/process_output_documents.rb
spec/services/process_output_documents_spec.rb

This ties together all the service and domain objects, going from creating a batch of output documents, rendering them as CSV and then uploading the CSV to the print house.

Add service object to process outstanding output documents

---

app/services/create_batch.rb
features/accessibility.feature
features/step_definitions/accessibility_steps.rb
features/support/matchers/expect_uploaded_csv_to_include.rb
spec/services/create_batch_spec.rb

The print house can't currently deal with braille or large text, so we
should not send output documents in those formats to them

Exclude braille and large text from batches

---

app/services/create_batch.rb
spec/services/create_batch_spec.rb

Includes chained `where` statements on top of a scope, which will be resolved in an upcoming PR.

Do not process non-uk appointment summaries

---

app/models/user.rb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb

It adds this link to the login page:
Which leads on to:
And finally:
The forms for these last 2 pages are the ones that ship with Devise. Do we care enough to rewrite them to be congruent with our styleguide? If so, do we want to rework the login form?
Also, are we ok with deploying the code change along with the database change or do we want to split this up into 2 deployments?

Self service password reset

---

app/models/appointment_summary.rb
app/models/batch.rb
app/services/create_batch.rb
app/services/process_output_documents.rb
db/migrate/20150427131314_remove_processed_at_from_batches.rb
db/migrate/20150427131639_add_uploaded_at_to_batches.rb
db/schema.rb
spec/models/appointment_summary_spec.rb
spec/models/batch_spec.rb
spec/services/create_batch_spec.rb
spec/services/process_output_documents_spec.rb

Simpler version of #149.
Changes less about the existing implementation, doesn't need pub/sub, fewer moving parts, fewer interdependencies.

Upload all unprocessed batches (option B)

---

app/services/create_batch.rb
app/services/process_output_documents.rb
app/services/upload_to_print_house.rb

Instead of performing everything with a block passed to `ActiveSupport::TaggedLogging#tagged` we can make use of the public API on offer and simply push and pop tags as we see fit. For better or for worse tags are [stored on Thread.current](https://github.com/rails/rails/blob/f046e8a70fe526ebcea88ea1d084eb4b634b653b/activesupport/lib/active_support/tagged_logging.rb#L46). It's up for debate wether this is a valid approach or not.
Produces the following output:
Apart from the SQL logging, the key stages logged are:
* start
* id and number of contents upon batch creation
* id of batch to be uploaded
* paths of individual files to be uploaded
* end
A simplification could be `CreateBatch` and `UploadToPrintHouse` accessing `Rails.logger` directly rather than setting an instance variable. …

Use tagged logging for key stages of PrintHouse integration

---

Gemfile
Gemfile.lock
app/services/upload_to_print_house.rb
spec/services/upload_to_print_house_spec.rb
spec/spec_helper.rb

Adds naïve fault tolerance to the print-house uploads. A more sophisticated implementation would add random exponential backoff, but I'm not sure its needed in this case. Thoughts?

Retry print-house uploads up to 5 times

---

app/views/appointment_summaries/preview.html.erb

The existing code still includes `id`, `created_at`, `updated_at` and `user_id`:
```ruby
> (AppointmentSummary.columns - [:id, :created_at, :updated_at, :user_id]).map(&:name)
=> ["id",
"created_at",
"updated_at",
"date_of_appointment",
"value_of_pension_pots",
"income_in_retirement",
"guider_organisation",
"guider_name",
"continue_working",
"unsure",
"leave_inheritance",
"wants_flexibility",
"wants_security",
"wants_lump_sum",
"poor_health",
"user_id",
"reference_number",
"address_line_1",
"address_line_2",
"address_line_3",
"town",
"county",
"postcode",
"title",
"first_name",
"last_name",
"format_preference",
"has_defined_contribution_pension",
"upper_value_of_pension_pots",
"value_of_pension_pots_is_approximate",
"country"]
```
The proposed:
```ruby
> …
```

Ignore id and timestamp columns correctly

---

app/assets/javascripts/postcode-lookup.js

It is misleading and causing confusion amongst guiders. It is also not used for mail routing, and Ideal-Postcodes recommends not using it.

Ignore county in postcode search response

---

app/models/csv_upload_job.rb
app/models/transliterated_appointment_summary.rb
features/step_definitions/covering_letter_steps.rb
features/step_definitions/record_of_guidance_contents_steps.rb
features/support/fixtures.rb
spec/models/transliterated_appointment_summary_spec.rb

The font we use to render output documents has a limited character set so we need to remove unsupported characters.

Approximate non-ASCII characters

---

.travis.yml
Gemfile
Gemfile.lock

We can use an API token for the CI user [per the documentation](http://docs.travis-ci.com/user/private-dependencies/#API-Token).
Consequence is that we have to fetch the dependencies via HTTPS, not SSH.

Use API token when accessing Github

---

features/step_definitions/covering_letter_steps.rb

`Hash#slice` requires a list of parameters, not an array.

Slice the hash correctly

---

app/domain/output_document.rb
spec/domain/output_document_spec.rb

There is no need to include 'United Kingdom' on address labels when sending the documents. We therefore only include the country if the customer has specified a non-UK address.
@andrewgarner do you think we need more test coverage for the CSV phase?

Conditionally include or exclude attendee_country

---

app/forms/appointment_summary_browser.rb
spec/forms/appointment_summary_browser_spec.rb

Prior to this change, the cucumber features were failing in Travis if
the current day falls within a range of dates that could not be parsed
in ISO or MDY specification.

Don't depend on specific postgres `DateStyle`

---

app/models/user.rb
app/services/user_admin_cli.rb
lib/tasks/user_admin.rake
spec/factories.rb
spec/services/user_admin_cli_spec.rb

Adds two rake tasks. One for listing existing users with the administrative
flag set and another for toggling the flag on a user specified by the provided
email address.

Rake tasks for User administration

---

.travis.yml

This isn't being observed, plus it isn't currently configured.

Remove Geckoboard build reporting

---

db/schema.rb

Running `rake db:migrate` inferred this relationship.

Add missing foreign key

---

app/domain/output_document.rb
spec/domain/output_document_spec.rb

This is a Royal Mail requirement for sending international post.

Generate output documents with non-UK countries in uppercase

---

Gemfile
Gemfile.lock

Since we use preloaded dynos we should actively highlight destructive
schema changes. Loading the `deprecated_columns` gem will warn for
migrations with persisted attributes not marked with the
`deprecated_columns` macro.

Warn on destructive migrations

---

config/environments/production.rb
lib/devise_tagged_logging.rb

This adds `[uid: 1]` prefixes to logging via rails tagged logging. This
is so we can track a user's steps through the application flow to check
if they've been recorded post-interview summaries correctly.
This is done via a rack middleware since using the regular
`config.log_tags` with a `proc` to retrieve information from cookies /
session is too far down the middleware chain, after
`Rails::Rack::Logger` is called. /shrug

[WIP] Tag logs with devise's `current_user`

---

app/controllers/appointment_summaries_controller.rb
app/views/appointment_summaries/_preview_form.html.erb
app/views/appointment_summaries/email_confirmation.html.erb
app/views/appointment_summaries/new.html.erb
config/routes.rb
features/email_confirmation.feature
features/step_definitions/back_from_preview_steps.rb
features/step_definitions/email_confirmation_steps.rb
features/step_definitions/preview_record_of_guidance_contents_steps.rb
features/step_definitions/record_of_guidance_contents_steps.rb
features/step_definitions/record_of_guidance_steps.rb
features/support/pages/email_confirmation_page.rb

Based on:
https://designnotes.blog.gov.uk/2015/09/15/make-sure-this-is-right-a-new-email-confirmation-pattern/ 
to improve percentage of correctly entered email addresses

Improve email reliability by asking for confirmation

---

app/jobs/notify_via_email.rb
config/initializers/notify.rb
spec/jobs/notify_via_email_spec.rb

Previously guiders could only send notifications 
to ineligible customers via post
This release will correspond with an update to guider notes, allowing them to send ineligible notifications via email if the customer opts into digital.

Send Ineligible template if customer is ineligible

---

app/controllers/appointment_summaries_controller.rb
app/forms/appointment_summary_browser.rb
app/forms/appointment_summary_finder.rb
app/models/user.rb
app/services/user_admin_cli.rb
app/views/appointment_summaries/index.html.erb
app/views/layouts/application.html.erb
config/initializers/date_formats.rb
config/routes.rb
db/migrate/20160901121801_add_role_to_user.rb
db/schema.rb
features/regenerate_summary_document.feature
features/step_definitions/appointment_summary_steps.rb
features/step_definitions/regenerate_summary_ocument_steps.rb
features/support/pages/appointment_summaries_page.rb
features/support/pages/appointment_summary_page.rb
lib/tasks/user_admin.rake
spec/factories.rb
spec/services/user_admin_cli_spec.rb

Allow Team leaders to regenerate a summary document. This creates a new summary document record with allow any of the details to be corrected if required.
The PR also removes the admin flag and replaces it with a role, at this stage users can only have a single role at any one time.

Regenerate summary document

---

app/controllers/admin/appointment_summaries_controller.rb
app/jobs/notify_via_email.rb
app/models/appointment_summary.rb
spec/controllers/admin/appointment_summaries_controller_spec.rb
spec/models/appointment_summary_spec.rb

* Don't raise NotificationAlreadySent error when trying to resend notification without changing the email address
* Cleaner message for NotificationAlreadySent - only return useful variables 
* Update email regex - use the regex used by notify

Allow resend with the same email address

---

app/models/appointment_summary.rb
spec/models/appointment_summary_spec.rb

Keep it inline with the Notify regex to avoid predictable
errors when sending the email across.
Difference to the notify regex:
* block '..' in regex - notify has a secondary check
* block spaces in email address

Update email regex

---

app/controllers/admin/appointment_summaries_controller.rb
app/controllers/appointment_summaries_controller.rb
spec/controllers/admin/appointment_summaries_controller_spec.rb

Remotely removing access to the application works
by removing the 'signin' permission from the users.
That means that a user with 'team_leader' permission
but with access blocked for the application would
still have been able to access the 'team_leader' sections
of the application.

Always require signin permission

---

Gemfile
Gemfile.lock
app/controllers/appointment_summaries_controller.rb
app/jobs/create_tap_activity.rb
app/views/appointment_summaries/done.html.erb
spec/jobs/create_tap_activity_spec.rb

Once a summary document has been created trigger
the appropriate activity to be created in TAP.
the following variables will need to be set:
```ruby
TELEPHONE_APPOINTMENTS_API_BEARER_TOKEN
TELEPHONE_APPOINTMENTS_API_URI
```
**Pending** Fix build pack

Create summary document activity in TAP

---

app/jobs/create_tap_activity.rb
spec/jobs/create_tap_activity_spec.rb

We currently have no way of knowing which actual appointment this refers to
so when these occur in production we are at a loss.

Include the appointment reference for debugging

---

app/controllers/appointment_summaries_controller.rb
app/views/appointment_summaries/summarise_via_tap.html.erb
spec/factories.rb

We should stop guiders from landing directly here and summarising
appointments by entering the TAP reference. When this happens, they
circumvent the status checks that occur in TAP and thus the outbound
webhook to create the TAP activity fails upon creation.
This change throws up a warning screen to the guider (team leaders are
still permitted) telling them to summarise the appointment from TAP.

Ensure appointments are summarised via TAP

---

.rubocop.yml
app/jobs/notify_delivery_check.rb
app/models/appointment_summary.rb
app/services/notify_delivery.rb
app/services/notify_delivery_checker.rb
db/migrate/20170222151348_add_notify_delivery_to_appointment_summaries.rb
db/schema.rb
spec/factories.rb
spec/jobs/notify_delivery_check_spec.rb
spec/services/notify_delivery_checker_spec.rb
spec/services/notify_delivery_spec.rb

We need to poll for notify email delivery statuses to ensure we remain
deliverable at all times. Unfortunately notify does not supply webhooks
so we have to poll for the statuses instead.
A summary will be included for polling when it's less than two days old,
has a notify supplied ID and its `notify_completed_at` timestamp is
absent. When notify deems itself 'done' with our notification whether
due to a permanent failure or delivery it will supply us with the
`completed_at` timestamp that we use to mark the summary for exclusion
next time around.
This will need to be scheduled `rails runner 'NotifyDeliveryChecker.new.call'`.

Poll for notify delivery statuses

---

Gemfile
Gemfile.lock
app/services/notify_delivery.rb
spec/services/notify_delivery_spec.rb

Ping TAP to create an activity when GOVUK notify tells us a summary
document delivery failed to deliver.
I've pinned to the unreleased GitHub gem for the timebeing while I wait for
ownership of the gem on rubygems.org.

Ping TAP when notify tells us a delivery failed

---

app/services/notify_delivery.rb
spec/services/notify_delivery_spec.rb

We need to pass the original booking reference to the API so we can
reconcile correctly between the two records.

Ensure we pass the correct reference to the API

---

app/jobs/notify_deliveries_check.rb
lib/tasks/scheduling.rake

This is a bit of a hack to workaround the heroku scheduler's limit on
running jobs at most once every ten minutes. When this newly introduced
rake task runs it will first schedule a check to run immediately, then
another 9 checks, covering each subsequent minute.

Check for notify deliveries every minute

---

app/controllers/appointment_summaries_controller.rb
config/routes.rb
features/support/pages/appointment_summary_page.rb
spec/features/tap_summary_document_generation_spec.rb

Lets guiders modify existing appointment summaries when the original
appointment record is updated in TAP. The previously persisted summary
details are bound to the form and are modifiable. When validated /
persisted we ping TAP to create another activity entry and if necessary
email the customer.

Permit regeneration of TAP appointment summaries

---

app/jobs/notify_via_email.rb
spec/jobs/notify_via_email_spec.rb

Now we can reissue the summaries we don't need to guard against
resending them.

Don't guard against resending of digital summary

---

app/jobs/notify_via_email.rb
spec/jobs/notify_via_email_spec.rb

We need to reset the timestamp and status to ensure once we have
reissued an appointment summary digitally via notify that we then poll
at the scheduled intervals for its delivery status. Prior to this
change, we were not resetting those markers against the record so it was
being skipped when determining which records to poll.

Ensure we poll for delivery status on resends

---

.travis.yml
Gemfile
Gemfile.lock
app/controllers/appointment_summaries_controller.rb
app/views/appointment_summaries/_preview_form.html.erb
app/views/appointment_summaries/new.html.erb
app/views/appointment_summaries/preview.html.erb
features/support/pages/done_page.rb
spec/features/tap_summary_document_generation_spec.rb
spec/rails_helper.rb
spec/support/database_rewinder.rb
spec/support/poltergeist.rb

Resolves a bug whereby previews were being skipped for postal summaries
when regenerating via TAP.

Ensure previews are displayed when regenerating

---

app/views/appointment_summaries/done.html.erb

This improves the information given to the guider
once they have created a summary document.

Alter the information on the 'done' page

---

.travis.yml

Any branch beginning with 'prototypes/*' won't run on travis

Exclude prototype branches from being run on travis

---

app/models/appointment_summary.rb
app/views/appointment_summaries/confirm.html.erb

This will display what supplementary info was selected
on the previous screen when creating the summary document.
This helps the guiders understand what will be displayed
in the summary document when sent out/printed

Add supplementary information to the confirmation screen

---

app/controllers/appointment_summaries_controller.rb
app/models/appointment_summary.rb
app/models/user.rb
app/services/appointment_summary_csv.rb
app/services/notify_delivery.rb
app/views/admin/appointment_summaries/index.html.erb
app/views/appointment_summaries/index.html.erb
app/views/appointment_summaries/new.html.erb
app/views/appointment_summaries/summarise_via_tap.html.erb
db/migrate/20170530133132_add_telephone_appointment_flag_to_appointment_summaries.rb
db/schema.rb
db/seeds.rb
spec/factories.rb
spec/features/accessibility_spec.rb
spec/features/appointment_summary_browser_spec.rb
spec/features/back_from_confirmation_spec.rb
spec/features/delivery_methods_spec.rb
spec/features/email_notification_spec.rb
spec/features/face_to_face_summary_creation_spec.rb
spec/features/ineligibility_letter_spec.rb
spec/features/phone_summary_creation_spec.rb
spec/features/record_of_guidance_contents_spec.rb
spec/features/record_of_guidance_spec.rb
spec/features/reprint_summary_spec.rb
spec/features/tap_summary_document_generation_spec.rb
spec/rails_helper.rb
spec/services/appointment_summary_csv_spec.rb
spec/services/notify_delivery_spec.rb
spec/support/pages/appointment_summary_page.rb

Changes to allow summaries for face to face bookings, allowing the form to be completed from scratch, without certain fields disabled as we do for tap.

Add functionality for face to face summaries

---

app/models/appointment_summary.rb
spec/models/appointment_summary_spec.rb

Appointments booked via other systems have alphanumeric reference numbers, so this allows sharing of the same values to be used for summary documents.

Loosen validation on reference number to allow any string

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/email-validation.js
app/assets/javascripts/init.js
app/assets/stylesheets/components/_ajax_loader.scss
app/assets/stylesheets/components/_button_link.scss
app/assets/stylesheets/components/_email_outer.scss
app/helpers/application_helper.rb
app/views/appointment_summaries/new.html.erb
spec/features/email_address_suggestions_spec.rb
spec/support/pages/appointment_summary_page.rb

Much the same as we've seen before in the other apps.
Styles recycled from `pension_guidance` with minor tweaking, but lead to replacing `sass-rails` with `sassc-rails` (as used in `pension_guidance`) because of unsupported syntax (definition if mixins within control flow statements).

Add Mailgun email validation to summary form

---

app/models/appointment_summary.rb
app/services/appointment_summary_csv.rb
app/services/csv_generator.rb
spec/services/appointment_summary_csv_spec.rb

Surfacing the `organisation_content_id` of the user who generated the summary under the column `content_id`.

Add organisation id to csv export

---

Gemfile
Gemfile.lock

Updating version of output-templates based on typo fixes to the summary
document

bumping output-templates version

---

Gemfile
Gemfile.lock
app/domain/output_document.rb
app/models/appointment_summary.rb
app/services/appointment_summary_csv.rb
app/views/appointment_summaries/new.html.erb
db/migrate/20170710142023_add_covering_letter_type_to_appointment_summaries.rb
db/schema.rb
spec/factories.rb
spec/services/appointment_summary_csv_spec.rb
spec/support/pages/appointment_summary_page.rb

Introduction of new options in the appointment summary form:
Resulting covering letter, "Section 32 arrangement"
Resulting covering letter, "Adjustable income pot in payment"
Resulting covering letter, "Inherited pension pot"

Add ability to customise covering letter content

---

Procfile

Take advantage of Heroku's release phase to run migrations
automatically.

Run migrations upon release

---

app/views/layouts/application.html.erb

This is not necessary and was passing potentially sensitive data to GA
via the UA plugin.

Remove GTM snippet

---

app/controllers/appointment_summaries_controller.rb
app/models/user.rb
app/views/appointment_summaries/new.html.erb
spec/controllers/appointment_summaries_controller_spec.rb
spec/factories.rb
spec/features/email_address_suggestions_spec.rb
spec/features/face_to_face_summary_creation_spec.rb
spec/features/phone_summary_creation_spec.rb
spec/support/pages/appointment_summary_page.rb

This allows both types of guiders (face-to-face or telephone) to summarise
appointments with the same signon account.

Allow general purpose guiders to summarise

---

app/views/appointment_summaries/new.html.erb
spec/features/face_to_face_summary_creation_spec.rb
spec/features/phone_summary_creation_spec.rb

When the field is marked with the `disabled` attribute it does not POST
a value, thus would be preselected as `standard` for the
`appointment_type`. This means some customers were missing out on vital
information pertaining to the pensionable age.
I also scoped the test helper methods as they were clobbering eachother
in the global namespace.

Correct issue with disabled/readonly field

---

app/models/appointment_summary.rb
spec/controllers/appointment_summaries_controller_spec.rb
spec/models/appointment_summary_spec.rb

Digital summaries should not be created when no email address was
specified.

Validate email presence when requesting digital

---

app/controllers/appointment_summaries_controller.rb

Previously if appointments had the same ID (rare but possible) they
could be linked incorrectly. This ensures that will not happen.

Ensure f2f/phone appointments are distinct

---

app/models/appointment_summary.rb

There are some instances of old data where the associated user is
missing or not synchronised from signon. This ensures the organisation
ID is accessed safely in those instances.

Work around missing users

---

Gemfile.lock

A calculator was inaccurate so was replaced by MAS. This update ensures
we point to the correct version.

Update output templates for signposting

---

Gemfile
Gemfile.lock
app/controllers/api/v1/searches_controller.rb
app/models/appointment_summary_search.rb
app/models/user.rb
app/serializers/appointment_summary_serializer.rb
config/application.rb
config/environment.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/gds_sso.rb
config/routes.rb
spec/factories.rb
spec/models/appointment_summary_search_spec.rb
spec/requests/api_searches_spec.rb
spec/support/user_helpers.rb

When provided with a query (reference or partial match on name/email) we
return the appointments matching the given critera. The attributes:
reference, name and URL are serialized and returned as JSON.

Provide a simple search API for appointments

---

app/models/appointment_summary.rb
app/services/redactor.rb
lib/tasks/confidentiality.rake
spec/services/redactor_spec.rb

Can now redact all records older than two years for GDPR compliance.

Script redactions for GDPR compliance

---

app/views/appointment_summaries/new.html.erb

This isn't valid on an radio element so should be removed. It appears to
have an affect on some browser/os combos as a guider is complaining they
cannot alter this field once set.

Remove the readonly attribute

---

app/controllers/appointment_summaries_controller.rb
app/jobs/braille_notification.rb
app/models/appointment_summary.rb
spec/controllers/appointment_summaries_controller_spec.rb
spec/jobs/braille_notification_spec.rb
spec/models/appointment_summary_spec.rb

Sends a notification email to the feedback inbox when a customer
requests a Braille document.

Notify accounts when Braille requested

---

.travis.yml
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/eligibility.js
app/models/appointment_summary.rb
app/views/appointment_summaries/new.html.erb
db/migrate/20201105164411_add_db_pot_attributes_to_appointment_summaries.rb
db/schema.rb
spec/factories.rb
spec/features/ineligibility_letter_spec.rb
spec/jobs/notify_via_email_spec.rb
spec/models/appointment_summary_spec.rb
spec/support/chrome.rb
spec/support/poltergeist.rb

Guiders can specify that the customer stated a DB pension and whether they
indicated to transfer their pot. This is for analysis at a later stage.

Allow guiders to specify DB pension options

---

app/models/appointment_summary.rb
spec/factories.rb

The customer should be ineligible if they specified a DB pension but did
not state they would transfer the pension.

Alter eligibility rules

---

lib/tasks/export.rake

This helps associate records across disparate systems.

Include the `reference_number` column for export

---

app/models/appointment_summary.rb
spec/models/appointment_summary_spec.rb

When the customer chooses digital delivery, we only need to capture the
postcode for data analysis. Not the whole address. For postal
appointments we always capture the full address components.

Always require postcode component

---

app/models/appointment_summary.rb
spec/models/appointment_summary_spec.rb

Because the country dropdown defaults to UK, when the change was made to
always validate postcodes, regardless of country of origin, the
validation is overzealous in that it should always validate the presence
of a given postcode, but only the format when it's UK.

Don't validate format of non-UK postcodes

---

config/initializers/sidekiq.rb

Heroku terminates the SSL connection to the redis instances using
self-signed certificates so we need to configure sidekiq's redis
connections to not verify.

Configure sidekiq's redis connection

---

app/controllers/appointment_summaries_controller.rb
app/views/appointment_summaries/tap_user_needs_phone_permission.html.erb
spec/features/tap_summary_document_generation_spec.rb
spec/support/pages/appointment_summary_page.rb

This will ensure TAP users cannot create incorrectly attributed
summaries if they do not have the correct permission. Prior to this
change these appointments were attributed to the face-to-face channel.

Ensure TAP users have the phone permission

---

app/controllers/api/v1/appointment_summaries_controller.rb
app/controllers/appointment_summaries_controller.rb
app/models/appointment_summary.rb
spec/controllers/appointment_summaries_controller_spec.rb

TAP ought to be notified for any phone appointment, regardless whether
it's a digital or postal summary.

Notify all TAP appointments

---

app/models/appointment_summary.rb
spec/models/appointment_summary_spec.rb

This can cause issues with the TAP integration since they're not normalised on each side. Requiring lowercase emails can mean that agents must re-enter the email in lowercase in TAP when it's provided by a customer in uppercase.

Allow uppercase email addresses

---

.travis.yml
app/views/appointment_summaries/new.html.erb

These fields were previously marked as readonly and now need to be editable for TAP reissuing.

Allow the first/last name and email edits

---

app/views/appointment_summaries/new.html.erb

This might help with agents using incorrect details when completing summary documents.

Turn autocomplete off

---

app/jobs/notify_via_email.rb
spec/jobs/notify_via_email_spec.rb

This appears in the printed or download versions but was always omitted from the email version. This change adds the 'covering letter' paragraph to the email content also.

Include 'covering letter' type content in email

---

Gemfile
Gemfile.lock
app/domain/output_document.rb
app/jobs/notify_via_email.rb
app/services/pdf_download_url_presenter.rb
app/views/appointment_summaries/new.html.erb
config/application.rb
config/initializers/notify.rb
db/migrate/20250519132353_add_welsh_to_appointment_summaries.rb
db/schema.rb
lib/tasks/summary_variant_pdfs.rake
spec/domain/output_document_spec.rb
spec/features/tap_due_diligence_summary_document_generation_spec.rb
spec/features/tap_summary_document_generation_spec.rb
spec/jobs/notify_via_email_spec.rb
spec/services/pdf_download_url_presenter_spec.rb
spec/support/pages/appointment_summary_page.rb

Permits Welsh summary documents in both forms - email and letter.
Handles TAP passing through the Welsh option when completing summary document records.

Welsh Summary Documents
